"""Compare FLOAT tower optimization results across multiple cases.

Prerequisite: you need at least two FLOAT result CSVs already produced (e.g.,
by running tasks/run_wisdem with different analysis YAMLs). Without them this
task has nothing to compare.

Reads the result CSV from each case listed in --csv_paths and produces a
single combined comparison (plots + JSON summary) against the reference case
selected by --ref_idx (default 0).

Example:
    python examples/05_tower_fatigue_optimized_comparison/task.py \\
        --flagfile=examples/05_tower_fatigue_optimized_comparison/config.cfg
"""

from absl import app
from absl import flags
from absl import logging

import pyfloat

FLAGS = flags.FLAGS

# General flags
flags.DEFINE_string("output_dir", None, "Folder to save output files.")
flags.DEFINE_integer("ref_idx", 0,
                     "Index of the reference case in the list of CSV paths.")

# Results flags
flags.DEFINE_list(
    "csv_paths", None,
    "Path to the CSV files generated by the FLOAT tower optimizations.")
flags.DEFINE_list("labels", None, "Custom labels for the tower cases.")

# Constraints flags
flags.DEFINE_string(
    "files_dir", None,
    "Path to the directory containing all necessary FLOAT input files.")
flags.DEFINE_string("analysis_filename", None,
                    "Name of the analysis YAML file (without .yaml).")

# Plot flags
flags.DEFINE_bool("save_svg", False, "If True, saves plots as SVG files.")

# Summary flags
flags.DEFINE_bool("save_summary", True,
                  "If True, saves JSON file with comparison.")
flags.DEFINE_bool("log_summary", True, "If True, prints comparison to console.")

flags.mark_flag_as_required("output_dir")
flags.mark_flag_as_required("files_dir")
flags.mark_flag_as_required("analysis_filename")
flags.mark_flag_as_required("csv_paths")
flags.mark_flag_as_required("labels")


def main(_):
    """Compare FLOAT tower optimization results."""
    labels = FLAGS.labels
    csv_paths = FLAGS.csv_paths

    manager = pyfloat.TowerWisdemManager(
        files_dir=FLAGS.files_dir, analysis_filename=FLAGS.analysis_filename)
    _, constraints_bounds = manager.get_design_constraints()
    _, design_variables_bounds = manager.get_design_variables()
    bounds = {**constraints_bounds, **design_variables_bounds}

    logging.info("Starting comparison of FLOAT tower results (ref=%s)...",
                 labels[FLAGS.ref_idx])

    comparator = pyfloat.TowerWisdemComparator(results_paths=csv_paths,
                                               output_dir=FLAGS.output_dir,
                                               labels=labels)
    comparator.plot_all(bounds=bounds, save_svg=FLAGS.save_svg)
    comparator.extract_summary_comparison(save_summary=FLAGS.save_summary,
                                          log_summary=FLAGS.log_summary,
                                          ref_idx=FLAGS.ref_idx)

    logging.info("Comparison between tower results completed.")


if __name__ == "__main__":
    logging.set_verbosity(logging.INFO)
    app.run(main)
